import path from "path";

const MATERIAL_PATTERNS = [
  { pattern: /\bPLA\+\b/i, value: "PLA+" },
  { pattern: /\bPLA\b/i, value: "PLA" },
  { pattern: /\bPETG\b/i, value: "PETG" },
  { pattern: /\bABS\b/i, value: "ABS" },
  { pattern: /\bASA\b/i, value: "ASA" },
  { pattern: /\bTPU\b/i, value: "TPU" },
  { pattern: /\bPC\b/i, value: "PC" },
  { pattern: /\bNYLON\b/i, value: "NYLON" },
  { pattern: /\bPA12\b/i, value: "PA12" },
  { pattern: /\bPA6\b/i, value: "PA6" },
  { pattern: /\bPA\b/i, value: "PA" },
  { pattern: /\bHIPS\b/i, value: "HIPS" },
  { pattern: /\bPVA\b/i, value: "PVA" }
];

export const normalizeMaterial = (value = "") => {
  const source = String(value).trim().toUpperCase();
  if (!source) return "";
  if (source.startsWith("PLA")) return "PLA";
  if (source.startsWith("PETG")) return "PETG";
  if (source.startsWith("ABS")) return "ABS";
  if (source.startsWith("ASA")) return "ASA";
  if (source.startsWith("TPU")) return "TPU";
  if (source.startsWith("PC")) return "PC";
  if (source.startsWith("NYLON")) return "NYLON";
  if (source.startsWith("PA12")) return "PA12";
  if (source.startsWith("PA6")) return "PA6";
  if (source.startsWith("PA")) return "PA";
  if (source.startsWith("HIPS")) return "HIPS";
  if (source.startsWith("PVA")) return "PVA";
  return source;
};

const inferMaterialFromText = (value = "") => {
  const normalized = String(value).replace(/[_-]+/g, " ");
  for (const { pattern, value: material } of MATERIAL_PATTERNS) {
    if (pattern.test(normalized)) return material;
  }
  return null;
};

const firstMatch = (content, patterns) => {
  for (const pattern of patterns) {
    const match = content.match(pattern);
    if (match?.[1]) return match[1].trim();
  }
  return null;
};

const parseDurationToMinutes = (value) => {
  if (!value) return 0;
  const colonTime = value.match(/^(\d+):(\d+):(\d+)$/);
  if (colonTime) {
    const [, h, m, s] = colonTime.map(Number);
    return Math.round((h * 3600 + m * 60 + s) / 60);
  }

  const hours = Number((value.match(/(\d+(?:\.\d+)?)\s*h/i) || [])[1] || 0);
  const minutes = Number((value.match(/(\d+(?:\.\d+)?)\s*m/i) || [])[1] || 0);
  const seconds = Number((value.match(/(\d+(?:\.\d+)?)\s*s/i) || [])[1] || 0);
  if (hours || minutes || seconds) {
    return Math.round((hours * 3600 + minutes * 60 + seconds) / 60);
  }

  const rawSeconds = Number(value);
  if (!Number.isNaN(rawSeconds) && rawSeconds > 0) {
    return Math.round(rawSeconds / 60);
  }

  return 0;
};

const parseNumber = (value) => {
  const num = Number(String(value || "").replace(",", "."));
  return Number.isFinite(num) ? num : 0;
};

const parseThumbnail = (content) => {
  const blockMatch = content.match(/;\s*thumbnail begin[^\n]*\n([\s\S]*?)\n;\s*thumbnail end/);
  if (!blockMatch?.[1]) return null;
  const base64 = blockMatch[1]
    .split("\n")
    .map((line) => line.replace(/^;\s?/, "").trim())
    .join("");
  return base64 ? `data:image/png;base64,${base64}` : null;
};

export const parseGcodeMetadata = ({ filename, content }) => {
  const estimatedRaw = firstMatch(content, [
    /;\s*TIME:(\d+)/i,
    /;\s*estimated printing time.*?=\s*([^\n\r]+)/i,
    /;\s*estimated_time\s*=\s*([^\n\r]+)/i
  ]);
  const weightRaw = firstMatch(content, [
    /;\s*filament used \[g\]\s*=\s*([^\n\r]+)/i,
    /;\s*total filament used \[g\]\s*=\s*([^\n\r]+)/i,
    /;\s*filament_weight_total\s*=\s*([^\n\r]+)/i
  ]);
  const materialFromMetadata = firstMatch(content, [
    /;\s*filament_type\s*=\s*([^\n\r]+)/i,
    /;\s*material\s*=\s*([^\n\r]+)/i,
    /;\s*filament_type\s*:\s*([^\n\r]+)/i,
    /;\s*material\s*:\s*([^\n\r]+)/i
  ]);
  const profile = firstMatch(content, [
    /;\s*generated by\s*(.+)/i,
    /;\s*slicer\s*=\s*([^\n\r]+)/i
  ]) || "Importado";

  const dimensionsX = parseNumber(firstMatch(content, [/;\s*MAXX:([^\n\r]+)/i, /;\s*model_x:\s*([^\n\r]+)/i]));
  const dimensionsY = parseNumber(firstMatch(content, [/;\s*MAXY:([^\n\r]+)/i, /;\s*model_y:\s*([^\n\r]+)/i]));
  const dimensionsZ = parseNumber(firstMatch(content, [/;\s*MAXZ:([^\n\r]+)/i, /;\s*object_height\s*=\s*([^\n\r]+)/i]));

  const name = path.basename(filename, path.extname(filename)).replace(/[_-]+/g, " ").trim();
  const material = inferMaterialFromText(materialFromMetadata) || inferMaterialFromText(filename) || "PLA";

  return {
    name,
    filename,
    material,
    estimatedMinutes: parseDurationToMinutes(estimatedRaw),
    weightGrams: parseNumber(weightRaw),
    profile,
    description: "Importado automaticamente desde archivo local.",
    compatibility: [],
    thumbnail: parseThumbnail(content) || "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80",
    dimensions: {
      x: dimensionsX,
      y: dimensionsY,
      z: dimensionsZ
    }
  };
};
